FreshShirts/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from contact.views import contact
from homepage.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('contact/', contact, name='contact'),
    path('about/', contact, name='about'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('product/', include('shop.urls', namespace='shop')),
    path('', homepage, name='homepage'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, "homepage.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fresh T-Shirts</title>


    <link rel="stylesheet" href="{% static 'js/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"> </script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"> </script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
  <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Fresh T-Shirts</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage' %}">Home
                        </a>
                    </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:product_list' %}">Products</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %} <! Start if statement for login and logout !>

                        <li  class="nav-item" {% if section == "dashboard" %}class="selected"{% endif %}> <a class="nav-link" href="{% url "dashboard" %}">Your account</a> </li>
                            {% if request.user.is_authenticated %}
                                     <a class="nav-link" href="{% url "logout" %}">Logout</a>
                            {% endif %}
                            {% else %}
                                    <a class="nav-link" href="{% url "login" %}">Log-in</a>
                    {% endif %} <! End if statement for login and logout !>
                <li class="nav-item">
                        {% with total_items=cart|length %}
                          {% if cart|length > 0 %}

                            <a class="nav-link" href="{% url "cart:cart_detail" %}">Your cart:
                              {{ total_items }} item{{ total_items|pluralize }},
                              ${{ cart.get_total_price }}
                            </a>
                          {% else %}
                          <a class="nav-link" href="#">  Your cart is empty.</a>
                          {% endif %}
                        {% endwith %}
                    </li>

                </ul>

            </div>
        </div>
    </nav> >
      Header - set the background image for the header in the line below -->

        <!-- Content section -->
    <section class="py-5">
        <div class="container">
            {% if messages %}
            <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">x</a>
            </li>
            {% endfor %}
            </ul>
            {% endif %}
            {% block content %}
            {% endblock %}

        <! THIS IS WHERE OUR CONTENT WILL BE DISPLAYED !>
        </div>
    </section>
    <section class="py-5 bg-image-full" style="background-image: url('http://greekcornerprinting.com/wp-content/uploads/2018/05/Home-page-banner-11.19.jpg');">
    <!-- Put anything you want here! There is just a spacer below for demo purposes! -->
    <div style="height: 200px;"></div>
    </section>
      <!-- Footer -->
        <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Our Store 2019</p>
        </div>
        <!-- /.container -->
        </footer>
</body>

</html>

templates/content.html
{% extends "base.html" %}
{% block content %}
          <h1>Welcome to Carmines T-Shirt Shop</h1>
          <p class="lead">Come buy shirts!</p>
          <p>Information about our store</p>
{% endblock %}

templates/homepage.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
          <h1>Welcome</h1>


{% endblock %}

templates/index.html
{% extends "base.html" %}